image: node:20-alpine

pipelines:
  branches:
    development:
      - step:
          name: Build and Deploy Frontend
          deployment: Production
          caches:
            - node
          script:
            - export VITE_BACKEND_URL=$BACKEND_URL
            - export VITE_REVERB_APP_KEY=$REVERB_APP_KEY
            - export VITE_REVERB_HOST=$REVERB_HOST
            - export VITE_REVERB_PORT=$REVERB_PORT
            - export VITE_REVERB_SCHEME=$REVERB_SCHEME
            - npm ci
            - npm run build
            - pipe: atlassian/rsync-deploy:0.13.0
              variables:
                USER: $SSH_USER
                SERVER: $SERVER_IP
                SSH_PORT: $SSH_PORT
                REMOTE_PATH: $DEPLOY_DIR
                LOCAL_PATH: dist/
                EXTRA_ARGS:
                  - "--delete" # Removes old/unused assets from server
